#!/bin/bash
echo "=== Railway Deployment Fix ==="
echo ""
echo "This script helps deploy the fix for Railway database connection issue."
echo ""

echo "1. Checking current git status..."
git status

echo ""
echo "2. Steps to deploy:"
echo ""
echo "   a. Commit the changes:"
echo "      git add ."
echo "      git commit -m 'Fix Railway database connection: update start scripts and Dockerfile'"
echo ""
echo "   b. Push to GitHub:"
echo "      git push origin main"
echo ""
echo "   c. On Railway:"
echo "      1. Go to your Nakama service"
echo "      2. Click 'Deployments' tab"
echo "      3. Click 'Clear build cache and redeploy'"
echo "      4. OR: Click 'Manual Deploy' → 'Deploy from GitHub'"
echo ""
echo "   d. Check Railway variables:"
echo "      1. Go to Nakama service → Variables tab"
echo "      2. Ensure these variables are set:"
echo "         PGHOST = \${{Postgres.PGHOST}}"
echo "         PGPORT = \${{Postgres.PGPORT}}"
echo "         PGUSER = \${{Postgres.PGUSER}}"
echo "         PGPASSWORD = \${{Postgres.PGPASSWORD}}"
echo "         PGDATABASE = \${{Postgres.PGDATABASE}}"
echo "         NAKAMA_RUNTIME_PATH = /nakama/data/modules"
echo "         NAKAMA_SERVER_KEY = [your-secure-key]"
echo ""
echo "   e. Monitor logs:"
echo "      1. Watch for '✅ Found Railway Postgres service variables'"
echo "      2. Watch for 'Running database migrations...'"
echo "      3. Watch for 'Starting Nakama server...'"
echo "      4. Ensure NO 'Error pinging database' messages"
echo ""
echo "3. Test deployment:"
echo "   curl https://[your-nakama-domain].up.railway.app/health"
echo "   # Should return: {\"status\":\"healthy\",\"service\":\"tic-tac-toe\",...}"
echo ""
echo "4. If still having issues:"
echo "   - Check RAILWAY-FIX-SUMMARY.md for troubleshooting"
echo "   - Run ./debug-railway.sh for diagnostics"
echo ""

echo "✅ Ready to deploy!"