#!/bin/bash

# LILA Tic-Tac-Toe - Deployment Guidance Script
# This script provides guidance for deploying the application, not full automation.

set -e

echo "=========================================="
echo "LILA Tic-Tac-Toe - Deployment Guidance"
echo "=========================================="
echo ""
echo "This script provides deployment guidance, not full automation."
echo "Follow these steps to deploy the application."
echo ""

# Check if we're in the right directory
if [ ! -f "docker-compose.yml" ]; then
    echo "❌ Error: Run this script from the project root directory."
    echo "   Current directory: $(pwd)"
    exit 1
fi

echo "📋 Deployment Overview"
echo "======================"
echo ""
echo "LOCKED PROVIDER CHOICE:"
echo "1. Frontend: GitHub Pages (via GitHub Actions)"
echo "2. Backend: Railway (Nakama with PostgreSQL)"
echo "3. Database: Railway PostgreSQL"
echo ""
echo "This repository is configured for Railway + GitHub Pages deployment."
echo "Both components must be deployed and configured to work together."
echo ""

echo "🚀 Step 1: Deploy Nakama Backend to Railway"
echo "==========================================="
echo ""
echo "1. Create Railway project and connect GitHub repository"
echo "2. Add PostgreSQL service (Railway provides DATABASE_URL)"
echo "3. Add Nakama service from GitHub:"
echo "   - Source: Your GitHub repository"
echo "   - **Set Root Directory to: /nakama** (in service settings)"
echo "   - Build/Start commands auto-detected from Dockerfile and start.sh"
echo ""
echo "   **Important**: Repository includes railway.json and nakama/start.sh"
echo "   for Railway compatibility. Set Root Directory to /nakama."
echo ""
echo "4. Configure Railway environment variables:"
echo "   - DATABASE_URL: Reference from PostgreSQL service"
echo "   - NAKAMA_RUNTIME_PATH: /nakama/data/modules"
echo "   - NAKAMA_SERVER_KEY: Generate secure key (NOT 'defaultkey')"
echo "   - NAKAMA_CORS_ORIGIN: Your GitHub Pages URL"
echo ""
echo "5. Railway automatically provides:"
echo "   - Public HTTPS domain with automatic TLS"
echo "   - Container build with embedded runtime module"
echo "   - Health checks and monitoring"
echo ""
echo "6. Verify backend is running:"
echo "   curl https://YOUR_RAILWAY_DOMAIN/health"
echo "   # Should return Nakama health status"
echo ""

echo "🌐 Step 2: Deploy Frontend to GitHub Pages"
echo "=========================================="
echo ""
echo "1. Push repository changes to GitHub"
echo "2. Configure GitHub Pages in repository settings:"
echo "   - Source: GitHub Actions"
echo "   - Branch: main"
echo ""
echo "3. Set GitHub repository Actions variables:"
echo "   - VITE_NAKAMA_HOST: Your Railway public domain"
echo "   - VITE_NAKAMA_USE_SSL: true"
echo "   - VITE_NAKAMA_SERVER_KEY: Same secure key as Railway"
echo "   - VITE_BASE_PATH: Repository name (for project Pages URLs)"
echo ""
echo "4. GitHub Actions workflow (.github/workflows/deploy-pages.yml) will:"
echo "   - Build frontend with correct base path"
echo "   - Deploy to GitHub Pages"
echo "   - Provide URL: https://username.github.io/repo-name/"
echo ""
echo "5. For custom domain (optional):"
echo "   - Update VITE_BASE_PATH to '/'"
echo "   - Configure custom domain in GitHub Pages settings"
echo ""

echo "🔗 Step 3: Connect Frontend to Backend"
echo "======================================"
echo ""
echo "1. Verify frontend can reach backend:"
echo "   - Test WebSocket connection to wss://YOUR_NAKAMA_SERVER:7350"
echo "   - Test HTTP API connection to https://YOUR_NAKAMA_SERVER:7350"
echo ""
echo "2. Update CORS if needed (in Nakama configuration)"
echo "   - Allow your frontend domain"
echo ""
echo "3. Test complete flow:"
echo "   - Open frontend URL"
echo "   - Create/join a room"
echo "   - Play a complete game"
echo "   - Test disconnect/reconnect"
echo ""

echo "📝 Step 4: Update README for Submission"
echo "======================================"
echo ""
echo "Before submission, update README.md with:"
echo "1. Public Frontend URL: [TO BE PROVIDED BEFORE SUBMISSION]"
echo "2. Deployed Nakama Endpoint: [TO BE PROVIDED BEFORE SUBMISSION]"
echo ""
echo "Replace the placeholder lines in the 'Submission-Time Values' section."
echo ""

echo "🔧 Optional: Local Testing Before Deployment"
echo "==========================================="
echo ""
echo "To test the production build locally:"
echo "1. Build frontend: cd web && npm run build"
echo "2. Serve locally: npx serve web/dist"
echo "3. Update .env with production-like values"
echo "4. Test with two browser windows"
echo ""

echo "⚠️  Important Notes"
echo "=================="
echo ""
echo "• This script does NOT automate deployment"
echo "• You must manually configure and deploy both components"
echo "• Browser-safe production requires HTTPS/WSS (TLS certificates)"
echo "• VITE_NAKAMA_HOST must be explicitly set (no fallback)"
echo "• Use secure values in production (SSL, non-default server key)"
echo "• Configure CORS on Nakama for your frontend domain"
echo "• Test thoroughly before marking as production-ready"
echo "• Monitor logs and metrics after deployment"
echo ""
echo "✅ Deployment guidance complete."
echo ""
echo "For local development, use: ./scripts/dev.sh"
echo ""

exit 0