#!/bin/bash

# LILA Tic-Tac-Toe - Deployment Guidance Script
# This script provides guidance for deploying the application, not full automation.

set -e

echo "=========================================="
echo "LILA Tic-Tac-Toe - Deployment Guidance"
echo "=========================================="
echo ""
echo "This script provides deployment guidance, not full automation."
echo "Follow these steps to deploy the application."
echo ""

# Check if we're in the right directory
if [ ! -f "docker-compose.yml" ]; then
    echo "❌ Error: Run this script from the project root directory."
    echo "   Current directory: $(pwd)"
    exit 1
fi

echo "📋 Deployment Overview"
echo "======================"
echo ""
echo "This application requires TWO deployment targets:"
echo "1. Frontend: Static web host (Vercel, Netlify, GitHub Pages, etc.)"
echo "2. Backend: Nakama server with PostgreSQL (cloud VM or container service)"
echo ""
echo "Both components must be deployed and configured to work together."
echo ""

echo "🚀 Step 1: Deploy Nakama Backend"
echo "================================"
echo ""
echo "1. Choose a hosting provider (AWS, GCP, Azure, DigitalOcean, etc.)"
echo "2. Set up a PostgreSQL database (version 15+ recommended)"
echo "3. Deploy Nakama server with the TypeScript runtime:"
echo ""
echo "   Option A: Use the provided Dockerfile:"
echo "     cd nakama"
echo "     docker build -t nakama-tic-tac-toe ."
echo "     # Then deploy the image to your container service"
echo ""
echo "   Option B: Manual deployment:"
echo "     - Install Nakama binary"
echo "     - Build TypeScript runtime: cd nakama && npm run build"
echo "     - Copy build/ directory to Nakama's runtime path"
echo ""
echo "4. Configure Nakama:"
echo "   - Set DATABASE_URL to your PostgreSQL connection string"
echo "   - Generate a secure server key (NOT 'defaultkey')"
echo "   - Configure SSL certificates for production"
echo "   - Set appropriate firewall rules (ports 7350, 7351)"
echo ""
echo "5. Verify backend is running:"
echo "   curl http://YOUR_SERVER:7350/health"
echo "   # Should return Nakama health status"
echo ""

echo "🌐 Step 2: Deploy Frontend"
echo "=========================="
echo ""
echo "1. Update environment variables for production:"
echo "   - Edit .env.production or set build-time variables"
echo "   - Set VITE_NAKAMA_HOST to your deployed Nakama server"
echo "   - Set VITE_NAKAMA_USE_SSL to true"
echo "   - Use your production server key"
echo ""
echo "2. Build the frontend:"
echo "   cd web"
echo "   npm install"
echo "   npm run build"
echo "   # Output will be in web/dist/"
echo ""
echo "3. Deploy to static hosting:"
echo "   Option A: Vercel"
echo "     vercel --prod"
echo ""
echo "   Option B: Netlify"
echo "     netlify deploy --prod"
echo ""
echo "   Option C: GitHub Pages"
echo "     # Configure GitHub Actions or manual deploy"
echo ""
echo "   Option D: S3 + CloudFront (AWS)"
echo "     aws s3 sync web/dist/ s3://YOUR_BUCKET"
echo "     # Configure CloudFront distribution"
echo ""

echo "🔗 Step 3: Connect Frontend to Backend"
echo "======================================"
echo ""
echo "1. Verify frontend can reach backend:"
echo "   - Test WebSocket connection to wss://YOUR_NAKAMA_SERVER:7350"
echo "   - Test HTTP API connection to https://YOUR_NAKAMA_SERVER:7350"
echo ""
echo "2. Update CORS if needed (in Nakama configuration)"
echo "   - Allow your frontend domain"
echo ""
echo "3. Test complete flow:"
echo "   - Open frontend URL"
echo "   - Create/join a room"
echo "   - Play a complete game"
echo "   - Test disconnect/reconnect"
echo ""

echo "📝 Step 4: Update README for Submission"
echo "======================================"
echo ""
echo "Before submission, update README.md with:"
echo "1. Public Frontend URL: [TO BE PROVIDED BEFORE SUBMISSION]"
echo "2. Deployed Nakama Endpoint: [TO BE PROVIDED BEFORE SUBMISSION]"
echo ""
echo "Replace the placeholder lines in the 'Submission-Time Values' section."
echo ""

echo "🔧 Optional: Local Testing Before Deployment"
echo "==========================================="
echo ""
echo "To test the production build locally:"
echo "1. Build frontend: cd web && npm run build"
echo "2. Serve locally: npx serve web/dist"
echo "3. Update .env with production-like values"
echo "4. Test with two browser windows"
echo ""

echo "⚠️  Important Notes"
echo "=================="
echo ""
echo "• This script does NOT automate deployment"
echo "• You must manually configure and deploy both components"
echo "• Use secure values in production (SSL, non-default server key)"
echo "• Test thoroughly before marking as production-ready"
echo "• Monitor logs and metrics after deployment"
echo ""
echo "✅ Deployment guidance complete."
echo ""
echo "For local development, use: ./scripts/dev.sh"
echo ""

exit 0